apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/env: stage
    app.kubernetes.io/project: test
spec:
  containers:
    - name: nginx
      image: nginx:alp

